# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wespeak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wespeak
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Alamofire', '~> 4.4'
  pod 'OpenTok'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'Cosmos'
  pod 'KDCircularProgress'
  pod 'FlagKit'
end
